### ISSUE TITLE
Is this correct?

### ISSUE THREAD

**Issue by rdurelli** [jfb-h/MainPaths.jl#6]
As can be noted SPLCEdge must be a subtype MainPathEdgeWeight, right?
`Base.@kwdef struct SPLCEdge <: MainPathVertexWeight`

https://github.com/jfb-h/MainPaths.jl/blob/613dcf1df8467886edb4834e689ba2c79dd2cd1b/src/weights_spc.jl#L164

**Comment by jfb-h** [comment]
You're right, I fixed it. Thanks!
